format = """
$os\
$username\
[](bg:surface1 fg:surface0)\
$directory\
[](fg:surface1) 
"""
# bg:sapphire)\
# $git_branch\
# $git_status\
# [](fg:sapphire bg:pink)\
# $c\
# $elixir\
# $elm\
# $golang\
# $gradle\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# $scala\
# [ ](fg:pink)\
# """

palette = 'catppuccin-mocha'

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:surface0 fg:sapphire"
style_root = "bg:surface0 fg:maroon"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:surface0"
disabled = true # Disabled by default

[directory]
style = "bg:surface1 fg:pink"
format = "[ $path ]($style)" # można dodać  󰉋
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:pink fg:mantle"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#74c7ec"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:pink fg:mantle"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:pink fg:mantle"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:sapphire fg:crust"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:sapphire fg:crust"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:pink fg:mantle"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:pink fg:mantle"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:pink fg:mantle"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:pink fg:mantle"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:pink fg:mantle"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:pink fg:mantle"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:pink fg:mantle"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:pink fg:mantle"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:pink fg:mantle"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#89b4fa"
format = '[ ♥ $time ]($style)'

[palettes.catppuccin-mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
maroon = "#eba0ac"
peach = "#fab387"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
